'use strict';
function crumbsHTML(){const home='<span data-crumb="oc">Главная</span>';const list='<span data-crumb="oc">Объекты оценки</span>';const obj='<span data-crumb="oc">Объект '+esc(OC.eni)+'</span>';
 if(state.view==='oc')return home+'<span>/</span>'+list+'<span>/</span><b>'+esc(OC.type)+'</b>';
 if(state.view==='oi'){const oi=OI.find(o=>o.id===state.openOi);const t=oi?(oi.kind==='realty'?'Литера '+esc(oi.letter)+' · '+esc(oi.name):esc(oi.name)):'';return home+'<span>/</span>'+list+'<span>/</span>'+obj+'<span>/</span><b>'+t+'</b>';}
 if(state.view==='ocform')return home+'<span>/</span>'+list+'<span>/</span>'+obj+'<span>/</span><b>Редактирование ОЦ</b>';
 return home+'<span>/</span>'+list+'<span>/</span>'+obj+'<span>/</span><b>Создание объекта</b>';}
function ctxPlate(){ if(state.view==='oi'){const oi=OI.find(o=>o.id===state.openOi);if(oi){const pend=(oi.notes||[]).filter(n=>!n.done).length;const isR=oi.kind==='realty';const v=oiVerbal(oi);return '<div class="ctx-plate ctx-oi"><span class="ctx-kind">ОЦ → '+(isR?'литера':'ОИ')+'</span><b>'+(isR?'Литера '+esc(oi.letter)+' · ':'')+esc(oi.name)+'</b>'+(isR?'<span class="ctx-chip">'+fmt(num(oi.areas.tp||0))+' м² общая</span><span class="ctx-chip">этажей: '+oi.floors+'</span><span class="ctx-chip '+v.c+'">'+v.t+'</span>':'')+'<span class="ctx-chip '+(pend?'':'ctx-ok')+'">'+(pend?pend+' невып. заметок':'заметки выполнены')+'</span><span class="ctx-back-hint">возврат — «К объекту оценки»</span></div>';}}
 if(state.view==='ocform')return '<div class="ctx-plate ctx-form"><span class="ctx-kind">Редактирование</span><b>ОЦ · '+esc(OC.type)+'</b><span class="ctx-chip">'+esc(OC.address)+'</span><span class="ctx-chip">'+esc(OC.status)+'</span></div>';
 if(state.view==='mech')return '<div class="ctx-plate ctx-form"><span class="ctx-kind">Создание</span><b>'+(state.mechKind==='МЕХ'?'Механизм':'Офисная техника')+'</b><span class="ctx-chip">'+(state.mechMode==='mono'?'монолит':'комплекс')+'</span></div>';
 return null; }
function updateCtxPlate(){const w=$('#ctxPlateWrap');if(w){const h=ctxPlate();w.innerHTML=h||'';w.style.display=h?'':'none';}}
function docPageHTML(d,n){ if(n===1||d.pages[n-1].kind==='title')return '<div class="pp-h">'+esc(d.type)+'</div><div class="pp-sub">'+esc(d.name)+' · страница 1</div><div class="sk-h"></div>'+[100,94,97,88].map(w=>'<div class="sk-line" style="width:'+w+'%"></div>').join('')+'<table class="sk-table"><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr></table><div class="sk-h" style="width:30%"></div>'+[96,90].map(w=>'<div class="sk-line" style="width:'+w+'%"></div>').join('');
 return '<div class="pp-sub" style="margin-top:0">'+esc(d.name)+' · страница '+n+'</div><div class="sk-h"></div>'+[100,92,96,85,93,60].map(w=>'<div class="sk-line" style="width:'+w+'%"></div>').join('')+ (n%2===0?'<table class="sk-table"><tr><td></td><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td></tr></table>':'') +'<div class="sk-h" style="width:34%"></div>'+[95,88].map(w=>'<div class="sk-line" style="width:'+w+'%"></div>').join('');}
function openTabOnly(scope,id){VS.openTabs[scope]=VS.openTabs[scope]||[];if(!VS.openTabs[scope].includes(id))VS.openTabs[scope].push(id)}
function openDocViewer(scope,id){if(!id)return;openTabOnly(scope,id);state.viewerDoc={scope:scope,id:id};state.viewer={mode:(state.viewer&&state.viewer.mode==='compare')?'compare':'doc'};render()}
function openPhotoViewer(oiId,pageIdx){VS.photos[oiId]=VS.photos[oiId]||{page:1,rot:0,scroll:0};if(pageIdx)VS.photos[oiId].page=pageIdx;state.openOi=oiId;state.letterEdit=false;state.view='oi';state.viewer={mode:'photo'};render()}
function openPhotoInPlace(oiId,idx){VS.photos[oiId]=VS.photos[oiId]||{page:1,rot:0,scroll:0};if(idx)VS.photos[oiId].page=idx;state.openOi=oiId;state.viewer={mode:'photo'};render()}
function vSt(){const v=state.viewer;if(!v)return null; if(v.mode==='doc'||v.mode==='compare'){const d=state.viewerDoc?docListFor(state.viewerDoc.scope).find(x=>x.id===state.viewerDoc.id):null;return d?(VS.docs[d.id]||(VS.docs[d.id]={page:1,rot:0,scroll:0})):null;} return VS.photos[state.openOi]||(VS.photos[state.openOi]={page:1,rot:0,scroll:0});}
function vPages(){const v=state.viewer;if(!v)return[]; if(v.mode==='doc'||v.mode==='compare'){const d=state.viewerDoc?docListFor(state.viewerDoc.scope).find(x=>x.id===state.viewerDoc.id):null;return d?d.pages:[];} return photoPages(OI.find(o=>o.id===state.openOi));}
function setVZoom(z){VS.zoom=Math.min(220,Math.max(40,z));const r=document.querySelector('[data-vribbon]');if(r)r.style.zoom=String(VS.zoom/100);document.querySelectorAll('.cmp-body').forEach(c=>c.style.zoom=String(VS.zoom/100));const l=document.querySelector('[data-zoomlabel]');if(l)l.textContent=VS.zoom+'%'}
/* Документы литеры = документы ОЦ для недвижимости */
function viewerScopes(oi){ if(oi&&oi.kind==='realty')return ['oc']; if(oi)return [oi.id,'oc']; return (state.view==='mech'?['mech-new']:['oc']); }
function viewerHTML(){ if(!state.viewer)return '';
 const mode=state.viewer.mode; const inOi=state.view==='oi'; const oi=inOi?currentOI():null;
 const scopes=viewerScopes(oi);
 if(mode!=='photo'){ let vd=state.viewerDoc; const all=[];scopes.forEach(sc=>{(VS.openTabs[sc]||[]).forEach(id=>all.push({scope:sc,id:id}))}); if(!vd||!all.some(x=>x.scope===vd.scope&&x.id===vd.id)){ vd=all.length?all[all.length-1]:null; state.viewerDoc=vd; } }
 const vd=state.viewerDoc; const d=vd?docListFor(vd.scope).find(x=>x.id===vd.id):null; if(d)ensureDocPages(d);
 const dSt=d?(VS.docs[d.id]||(VS.docs[d.id]={page:1,rot:0,scroll:0})):null;
 const pages=oi?photoPages(oi):[]; const groups=oi?photoGroups(oi):[];
 const pSt=oi?(VS.photos[oi.id]||(VS.photos[oi.id]={page:1,rot:0,scroll:0})):null;
 const curPhoto=pages[pSt?Math.min(pSt.page,pages.length)-1:0];
 const modeBar=inOi?'<div class="vmode"><button class="vmode-btn '+(mode==='photo'?'active':'')+'" data-vmode="photo">Фото · '+pages.length+'</button><button class="vmode-btn '+(mode==='doc'?'active':'')+'" data-vmode="doc">Документы</button><button class="vmode-btn '+(mode==='compare'?'active':'')+'" data-vmode="compare">Сравнение</button></div>':'';
 let tabsBar='',toolbar='',body='';
 if(mode==='photo'){
   toolbar='<div class="vtoolbar"><div class="tool-group"><button class="tool-btn" data-vprev>‹</button><input class="page-input" data-vpage value="'+Math.min(pSt.page,pages.length||1)+'"><span class="muted">/ '+pages.length+'</span><button class="tool-btn" data-vnext>›</button></div><div class="tool-group"><select class="select vcat" data-vjump><option value="">К категории…</option>'+groups.map(g=>'<option value="'+esc(g.cat)+'">'+esc(g.cat)+' · '+g.items.length+'</option>').join('')+'</select></div><div class="tool-group"><button class="tool-btn" data-vrot>⟳</button></div><div class="tool-group"><button class="tool-btn" data-vzoom->−</button><span class="zoom-label" data-zoomlabel>'+VS.zoom+'%</span><button class="tool-btn" data-vzoom+>+</button></div><div class="tool-group right">'+(state.photoSel.length?'<button class="btn btn-ghost btn-sm" data-move-start>Прикрепить к… ('+state.photoSel.length+')</button>':'')+'<span class="vtitle">Фото · '+esc(curPhoto?curPhoto.cat:'—')+'</span><button class="tool-btn" data-vclose>×</button></div></div>';
   let gi=0;
   const ribbon=groups.map(g=>{const inner=g.items.map(it=>{gi++;return '<div class="vpage-wrap" data-vpageblk="'+gi+'"><div class="vpage photo-page" data-vpageinner style="transform:rotate('+pSt.rot+'deg)"><div class="photo-fill">'+esc(it.cat)+' · фото '+(it.i+1)+'</div></div></div>'}).join('');return '<div class="vgroup-h">'+esc(g.cat)+' · '+g.items.length+'</div>'+inner}).join('')||'<div class="vpage photo-page"><div class="photo-fill">Фото не загружены</div></div>';
   const rail=groups.map(g=>'<div class="rail-cat">'+esc(g.cat)+'</div>'+g.items.map(it=>{const idx=pages.findIndex(p=>p.cat===it.cat&&p.i===it.i)+1;const sel=state.photoSel.some(s=>s.oi===oi.id&&s.cat===it.cat&&s.i===it.i);return '<div class="vthumb pho '+(idx===pSt.page?'active':'')+(sel?' sel':'')+'" data-vthumb="'+idx+'" data-psel="'+oi.id+'|'+esc(it.cat)+'|'+it.i+'" title="'+esc(it.cat)+' '+(it.i+1)+' (Ctrl+клик — выбрать для переноса)"><span class="vthumb-num">'+idx+'</span></div>'}).join('')).join('');
   body='<div class="vbody"><div class="vrail"><div class="vrail-list">'+rail+'</div></div><div class="vstage" data-vstage><div class="vribbon" data-vribbon>'+ribbon+'</div></div></div>';
 } else if(mode==='doc'){
   if(!d){ toolbar='<div class="vtoolbar"><div class="tool-group right"><span class="vtitle">Документы</span><button class="tool-btn" data-vclose>×</button></div></div>'; body='<div class="vempty"><div class="vempty-box">Нет прикреплённых документов</div><button class="btn btn-primary" data-attach-default>Прикрепить файл</button></div>'; }
   else{ const all=[];scopes.forEach(sc=>{(VS.openTabs[sc]||[]).forEach(id=>{const t=docListFor(sc).find(x=>x.id===id);if(t)all.push({sc:sc,t:t})})}); const remaining=[];scopes.forEach(sc=>{docListFor(sc).forEach(t=>{if(!(VS.openTabs[sc]||[]).includes(t.id))remaining.push({sc:sc,t:t})})});
     tabsBar='<div class="vtabs">'+all.map(x=>'<button class="vtab '+(vd&&vd.scope===x.sc&&vd.id===x.t.id?'active':'')+'" data-vtab="'+x.sc+'|'+x.t.id+'">'+scopeLabel(x.sc)+' · '+esc(x.t.type)+(all.length>1?'<span data-vtabclose="'+x.sc+'|'+x.t.id+'">×</span>':'')+'</button>').join('')+(remaining.length?'<div class="dd"><button class="btn btn-ghost btn-sm" data-dd-toggle style="margin:0 0 4px 4px">+ документ</button><div class="dd-menu">'+remaining.map(x=>'<button data-vaddtab="'+x.sc+'|'+x.t.id+'">'+scopeLabel(x.sc)+' · '+esc(x.t.type)+' · '+esc(x.t.name)+'</button>').join('')+'</div></div>':'')+'</div>';
     toolbar='<div class="vtoolbar"><div class="tool-group"><button class="tool-btn" data-vprev>‹</button><input class="page-input" data-vpage value="'+dSt.page+'"><span class="muted">/ '+d.pages.length+'</span><button class="tool-btn" data-vnext>›</button></div><div class="tool-group"><button class="tool-btn" data-vrot>⟳</button></div><div class="tool-group"><button class="tool-btn" data-vzoom->−</button><span class="zoom-label" data-zoomlabel>'+VS.zoom+'%</span><button class="tool-btn" data-vzoom+>+</button></div><div class="tool-group right"><span class="vtitle">'+esc(d.type)+' · '+esc(d.name)+'</span><button class="tool-btn" data-vclose>×</button></div></div>';
     body='<div class="vbody"><div class="vrail"><div class="vrail-list">'+d.pages.map((p,i)=>'<div class="vthumb doc '+(i+1===dSt.page?'active':'')+'" data-vthumb="'+(i+1)+'" title="Страница '+(i+1)+'"><button class="vthumb-del" data-vdelpage="'+(i+1)+'">×</button><span class="vthumb-num">'+(i+1)+'</span></div>').join('')+'</div><button class="btn btn-ghost btn-sm" data-vaddpage style="margin:6px">+ Страница</button></div><div class="vstage" data-vstage><div class="vribbon" data-vribbon>'+d.pages.map((p,i)=>'<div class="vpage-wrap" data-vpageblk="'+(i+1)+'"><div class="vpage" data-vpageinner style="transform:rotate('+dSt.rot+'deg)">'+docPageHTML(d,i+1)+'</div></div>').join('')+'</div></div></div>';
   }
 } else { /* compare: две прокручиваемые ленты, клик выбирает независимо */
   toolbar='<div class="vtoolbar"><div class="tool-group"><button class="tool-btn" data-vzoom->−</button><span class="zoom-label" data-zoomlabel>'+VS.zoom+'%</span><button class="tool-btn" data-vzoom+>+</button></div><div class="tool-group right"><span class="vtitle">Сравнение: листайте и кликайте</span><button class="tool-btn" data-vclose>×</button></div></div>';
   const phList=pages.map((p,i)=>'<div class="cmp-item '+(i+1===pSt.page?'active':'')+'" data-cmp-photo="'+(i+1)+'"><div class="cap">'+esc(p.cat)+' · фото '+(p.i+1)+'</div><div class="ph-fill">'+esc(p.cat)+'</div></div>').join('')||'<div class="muted">Нет фото</div>';
   const dcList=d?d.pages.map((p,i)=>'<div class="cmp-item '+(i+1===dSt.page?'active':'')+'" data-cmp-doc="'+(i+1)+'"><div class="cap">'+esc(d.type)+' · стр '+(i+1)+'</div>'+docPageHTML(d,i+1)+'</div>').join(''):'<div class="muted">Откройте документ</div>';
   body='<div class="cmp" data-cmp><div class="cmp-col"><div class="cmp-h">ФОТО · '+esc(oi?oi.letter:'')+' · '+pages.length+'</div><div class="cmp-body" data-cmp-ph>'+phList+'</div></div><div class="cmp-col"><div class="cmp-h">'+(d?esc(d.type):'ДОКУМЕНТ')+'</div><div class="cmp-body" data-cmp-doc-body>'+dcList+'</div></div></div>';
 }
 return '<div class="viewer">'+modeBar+tabsBar+toolbar+body+'</div>';
}
/* Мастер переноса фото между литерами */
function moveWizardHTML(){
  const mw=state.moveWizard; const src=OI.find(o=>o.id===mw.src);
  if(mw.step==='pick'){
    const q=norm(mw.query||'');
    const lits=OI.filter(o=>o.kind==='realty'&&o.id!==mw.src&&(!q||norm(o.letter+' '+o.name).includes(q)));
    return '<div class="move-wizard"><div class="card-head"><h3>Прикрепить фото к литере</h3><span class="hint">выбрано: '+mw.items.length+'</span><button class="tool-btn" data-move-cancel style="margin-left:auto">×</button></div>'+
      '<input class="input mw-search" data-mw-query placeholder="Поиск литеры (буква или название)" value="'+esc(mw.query||'')+'">'+
      (lits.map(o=>'<div class="mw-lit" data-mw-lit="'+o.id+'"><span class="letter-badge">'+esc(o.letter)+'</span><span>'+esc(o.name)+'</span><span class="pill-mini">'+photoPages(o).length+' фото</span></div>').join('')||'<div class="note-empty">Не найдено</div>')+
      '</div>';
  }
  const target=OI.find(o=>o.id===mw.target);
  const buckets=PHOTO_CAT.map(c=>({cat:c,items:mw.items.filter(it=>it.to===c)}));
  return '<div class="move-wizard"><div class="card-head"><h3>Распределение по категориям → Лит '+esc(target.letter)+'</h3><span class="hint">перетащите или выберите+категория</span><button class="tool-btn" data-move-cancel style="margin-left:auto">×</button></div>'+
    buckets.map(b=>'<div class="mw-bucket" data-bucket="'+esc(b.cat)+'"><div class="mw-bucket-h">'+esc(b.cat)+' · '+b.items.length+'</div>'+b.items.map(it=>'<span class="mw-chip" draggable="true" data-chip="'+it.key+'" data-cat="'+esc(it.cat)+'">'+esc(it.cat)+' '+ (it.i+1) +'</span>').join('')+'</div>').join('')+
    '<div class="inline-row"><select class="select" data-mw-cat style="max-width:200px">'+PHOTO_CAT.map(c=>'<option>'+esc(c)+'</option>').join('')+'</select><button class="btn btn-ghost btn-sm" data-mw-assign>В категорию выбранные</button><button class="btn btn-primary" data-move-confirm style="margin-left:auto">Подтвердить перенос</button></div></div>';
}
function splitWrap(viewerInner,growInner){ if(!viewerInner)return '<div class="split" style="--vw:0%"><div class="grow" style="padding-left:0">'+growInner+'</div></div>'; return '<div class="split">'+viewerInner+'<div class="vsplit" data-vsplit title="Потяните"></div><div class="grow">'+growInner+'</div></div>'; }
function noteRowHTML(scope,n){return '<div class="note-row '+(n.done?'done':'')+'"><input type="checkbox" data-note-check="'+scope+'|'+n.id+'" '+(n.done?'checked':'')+'><input class="note-input" data-note-edit="'+scope+'|'+n.id+'" value="'+esc(n.text)+'" placeholder="'+NOTE_DEFAULT+'"><span class="note-del" data-note-del="'+scope+'|'+n.id+'">×</span></div>'}
function notesGroupAcc(scope,label,notes,opts){opts=opts||{};const list=notes||[];const c=noteCounts(scope);const open=opts.open!==undefined?opts.open:state.accOpen['grp|'+scope]===true;const doneOpen=!!state.doneOpen[scope];
 return '<div class="acc '+(open?'open':'')+'"><div class="acc-head" data-acc-toggle="grp|'+scope+'"><span class="chev">▾</span>'+label+'<span class="pill-mini '+(c.p?'pill-pend':'pill-done')+'" data-notecount-pend="'+scope+'">'+c.p+' невып.</span>'+(c.d?'<span class="pill-mini pill-done" data-notecount-done="'+scope+'">'+c.d+' вып.</span>':'')+'<button class="btn btn-ghost btn-sm" data-note-add="'+scope+'" style="margin-left:auto">+ Заметка</button></div><div class="acc-body"><div class="notes-list">'+(list.filter(n=>!n.done).map(n=>noteRowHTML(scope,n)).join('')||'<div class="note-empty">'+(opts.emptyPending||'Невыполненных заметок нет.')+'</div>')+'</div>'+(c.d?'<button class="done-toggle '+(doneOpen?'open':'')+'" data-done-toggle="'+scope+'"><span class="chev">▸</span> Выполненные <span class="pill-mini pill-done">'+c.d+'</span></button><div class="done-list" '+(doneOpen?'':'hidden')+'><div class="notes-list">'+list.filter(n=>n.done).map(n=>noteRowHTML(scope,n)).join('')+'</div></div>':'')+'</div></div>';}
function drawerNotesHTML(){const groups=[{scope:'oc',label:'ОЦ',notes:OC.notes||[]}].concat(OI.map(o=>({scope:o.id,label:oiLabel(o),notes:o.notes||[]})));return '<div class="drawer-head">Заметки по объекту</div>'+groups.map(g=>'<div class="nb-group">'+notesGroupAcc(g.scope,g.label,g.notes)+'</div>').join('')}
function photoAccordions(oi,withAdd){const cats=Object.keys(oi.photos||{});if(!cats.length)return '<span class="muted">Фото не загружены</span>';return cats.map((cat,ci)=>{const key='ph|'+oi.id+'|'+cat;const isOpen=state.accOpen[key]===true;return '<div class="acc '+(isOpen?'open':'')+'"><div class="acc-head" data-acc-toggle="'+key+'"><span class="chev">▾</span>'+esc(cat)+'<span class="muted" style="font-weight:400">'+oi.photos[cat]+' фото</span></div><div class="acc-body"><div class="ph-row">'+Array.from({length:oi.photos[cat]},(_,i)=>'<div class="ph" data-open-photo="'+oi.id+'|'+esc(cat)+':'+i+'">'+esc(cat)+' '+(i+1)+'</div>').join('')+(withAdd?'<button class="btn btn-ghost btn-sm" data-add-photo="'+esc(cat)+'">+ Загрузить</button>':'')+'</div></div></div>'}).join('')}
function photoSectionsHTML(){const q=state.photoQuery||'';const letters=OI.filter(o=>o.kind==='realty');const sections=letters.map(oi=>{const pages=photoPages(oi).map((p,i)=>({cat:p.cat,i:p.i,idx:i})).filter(p=>photoMatches(oi,p.cat,p.idx,q));if(!pages.length)return '';return '<div class="photo-sec"><div class="photo-sec-h">Литера '+esc(oi.letter)+' · '+esc(oi.name)+' <span class="tag-mini">'+pages.length+'</span></div><div class="tile-grid">'+pages.map(p=>'<div class="tile" data-tile-photo="'+oi.id+'|'+p.idx+'" data-tile-sel="'+oi.id+'|'+esc(p.cat)+'|'+p.i+'" title="ЛКМ — открыть; Ctrl+ЛКМ — выбрать для переноса"><div class="tile-img">'+esc(p.cat)+'</div><div class="tile-cap">'+esc(p.cat)+' · фото '+(p.i+1)+'</div></div>').join('')+'</div></div>'}).join('');return sections||'<div class="note-empty">Ничего не найдено по запросу «'+esc(q)+'».</div>'}
function photosTab(){return splitWrap((state.viewer&&state.viewer.mode==='photo')?viewerHTML():null,'<div class="card t-blue"><div class="card-head"><span class="card-idx">03</span><h3>Фото по литерам</h3><span class="hint">плитки; ЛКМ — открыть, Ctrl+ЛКМ — выбрать для переноса</span><input class="input" id="photoSearch" style="margin-left:auto;max-width:340px" placeholder="Напр.: Лит А фасад" value="'+esc(state.photoQuery||'')+'"></div><div class="card-pad" id="photoSections">'+photoSectionsHTML()+'</div></div>')}
function oiAccordion(oi){return '<div style="padding:4px 2px"><div class="acc-inner"><div class="sec-h">Основные параметры</div><div class="params-grid"><div class="grid g-4"><div class="field"><label>Общая площадь (ТП)</label><b>'+esc(oi.areas&&oi.areas.tp?oi.areas.tp:'—')+' м²</b></div><div class="field"><label>Этажей</label><b>'+(oi.floors||'—')+'</b></div><div class="field"><label>Тип строения</label><b>'+esc(oi.buildType||'—')+'</b></div><div class="field"><label>Категория/класс</label><b>'+esc(autoCategory(oi))+'</b></div></div></div></div><div class="acc-inner"><div class="sec-h">Фотографии по категориям</div>'+photoAccordions(oi,true)+'</div></div>'}
function tableOI(){const rows=OI.filter(o=>o.kind!=='land');const land=OI.find(o=>o.kind==='land');
 return '<div class="card t-blue" style="margin-top:12px"><div class="card-head" data-card-toggle><span class="card-idx">02</span><h3>Перечень ОИ</h3><span class="hint">клик по строке — карточка; шеврон — аккордеон</span><button class="btn btn-primary btn-sm" data-add-letter style="margin-left:auto">+ Добавить литеру</button><span class="chev">▾</span></div><div class="card-body-wrap"><table class="tbl"><colgroup><col style="width:86px"><col><col style="width:150px"><col style="width:110px"><col style="width:100px"><col style="width:130px"><col style="width:100px"><col style="width:120px"></colgroup><thead><tr><th>Литера</th><th>Наименование</th><th>Категория</th><th>Статус</th><th>Общая площадь</th><th>Код ЕНИ</th><th>Фото</th><th>Действия</th></tr></thead><tbody>'+rows.map(o=>{const isR=o.kind==='realty';const expanded=!!state.expanded[o.id];const chev=isR?'<button class="chev-btn '+(expanded?'open':'')+'" data-acc-btn="'+o.id+'">▸</button>':'';const lit=isR?chev+esc(o.letter):'<span class="tag-mini">'+(o.kind==='vehicle'?'ТС':o.kind==='office'?'Офис. техника':'Механизм')+'</span>';const area=isR?(o.areas&&o.areas.tp?fmt(num(o.areas.tp))+' м²':'—'):'—';
  return '<tr class="rowlink" data-open-oi="'+o.id+'" '+(isR?'data-acc-id="'+o.id+'"':'')+'><td '+(isR?'data-acc-cell="'+o.id+'"':'')+'>'+lit+'</td><td>'+esc(o.name)+'</td><td class="ell">'+esc(autoCategory(o))+'</td><td>'+esc(o.status||'—')+'</td><td>'+area+'</td><td style="font-family:ui-monospace,Menlo,monospace;font-size:11.5px">'+esc(o.eni)+'</td><td>'+(isR?miniThumbs(o):'<span class="muted">—</span>')+'</td><td><div class="row-actions"><button class="btn btn-ghost btn-sm" data-open-oi="'+o.id+'">Открыть</button>'+(isR?'<button class="btn btn-danger btn-sm" data-del-oi="'+o.id+'">×</button>':'')+'</div></td></tr>'+(isR&&expanded?'<tr class="acc-row" data-accrow="'+o.id+'"><td colspan="8">'+oiAccordion(o)+'</td></tr>':'')}).join('')+'</tbody></table><div class="card-pad" style="border-top:1px solid var(--line-soft);padding-top:8px"><div class="sec-h teal" style="margin:0 0 6px">Земельный участок</div>'+(land?'<table class="tbl"><thead><tr><th>Назначение</th><th style="width:120px">Площадь</th><th>ЕНИ</th><th>Действия</th></tr></thead><tbody><tr class="clickable" data-open-oi="'+land.id+'"><td>'+esc(land.purpose)+'</td><td>'+fmt(num(land.area))+' м²</td><td style="font-family:ui-monospace,Menlo,monospace;font-size:11.5px">'+esc(land.eni)+'</td><td><div class="row-actions"><span class="rowchev-open">›</span></div></td></tr></tbody></table>':'<span class="muted">Не добавлен.</span>')+'</div></div></div>'}
function miniThumbs(oi){const pages=photoPages(oi);if(!pages.length)return '<span class="muted">—</span>';return '<div class="inline-row" style="gap:4px">'+pages.slice(0,3).map(p=>'<div class="ph-mini" data-open-photo="'+oi.id+'|'+p.cat+':'+p.i+'"></div>').join('')+'<span class="tag-mini">'+pages.length+'</span></div>'}
function ownersUsersHTML(){return '<div class="grid g-2"><div class="field"><label>Собственники</label><div class="inline-row">'+OC.owners.map((o,i)=>'<span class="ms-tag">'+esc(o)+'<span data-owner-rm="'+i+'">×</span></span>').join('')||'<span class="muted">не указаны</span>'+'<button class="btn btn-ghost btn-sm" data-add-party="owner">+ Добавить</button></div></div><div class="field"><label>Пользователь</label><div class="inline-row">'+OC.users.map((o,i)=>'<span class="ms-tag">'+esc(o)+'<span data-user-rm="'+i+'">×</span></span>').join('')||'<span class="muted">не указан</span>'+'<button class="btn btn-ghost btn-sm" data-add-party="user">+ Добавить</button></div></div></div>'}
function responsiblesHTML(){const ps=(k,l)=>'<div class="field"><label>'+l+'</label><select class="select" data-resp="'+k+'">'+PEOPLE.map(p=>'<option '+(p===OC.resp[k]?'selected':'')+'>'+esc(p)+'</option>').join('')+'</select></div>';return '<div class="grid g-4">'+ps('gov','Ответственный от гос. учреждения')+ps('cod','Оператор ЦОД')+ps('appr','Оценщик')+ps('insp','Осмотрщик')+'</div>'}
function partiesOC(){return '<div class="card t-slate" style="margin-top:12px"><div class="card-head" data-card-toggle><span class="card-idx">01</span><h3>Учреждение, собственники и ответственные</h3><span class="chev">▾</span></div><div class="card-body-wrap"><div class="card-pad"><div class="grid g-4"><div class="field"><label>Учреждение</label><b>'+esc(OC.institution)+'</b></div><div class="field"><label>Подвед</label><b>'+esc(OC.podved)+'</b></div><div class="field"><label>Собственники</label><div class="inline-row">'+OC.owners.map((o,i)=>'<span class="ms-tag">'+esc(o)+'<span data-owner-rm="'+i+'">×</span></span>').join('')||'<span class="muted">не указаны</span>'+'<button class="btn btn-ghost btn-sm" data-add-party="owner">+ Добавить</button></div></div><div class="field"><label>Пользователь</label><div class="inline-row">'+OC.users.map((o,i)=>'<span class="ms-tag">'+esc(o)+'<span data-user-rm="'+i+'">×</span></span>').join('')||'<span class="muted">не указан</span>'+'<button class="btn btn-ghost btn-sm" data-add-party="user">+ Добавить</button></div></div></div><div class="sec-h">Ответственные (без юриста)</div>'+responsiblesHTML()+'</div></div></div>'}
function docsTableHTML(withDel){return '<table class="tbl"><colgroup><col style="width:150px"><col><col style="width:90px"><col style="width:'+(withDel?60:40)+'px"></colgroup><thead><tr><th>Тип</th><th>Наименование</th><th>Дата</th><th></th></tr></thead><tbody>'+DOCS.map(d=>'<tr class="clickable" data-open-doc="'+d.id+'"><td><span class="tag-mini">'+esc(d.type)+'</span></td><td class="ell">'+esc(d.name)+'</td><td>'+esc(d.date)+'</td><td><div class="row-actions">'+(withDel?'<button class="btn btn-danger btn-sm" data-doc-del="'+d.id+'">×</button>':'')+'<span class="rowchev-open">›</span></div></td></tr>').join('')+'</tbody></table>'}
function docsBlockInner(oi,scope){return '<table class="tbl"><thead><tr><th style="width:130px">Тип</th><th>Наименование</th><th style="width:90px">Дата</th><th style="width:40px"></th></tr></thead><tbody>'+( (oi.docs||[]).map(d=>'<tr class="clickable" data-open-movdoc="'+scope+'|'+d.id+'"><td><span class="tag-mini">'+esc(d.type)+'</span></td><td class="ell">'+esc(d.name)+'</td><td>'+esc(d.date)+'</td><td><span class="rowchev-open">›</span></td></tr>').join('')||'<tr><td colspan="4" class="muted">Нет документов</td></tr>')+'</tbody></table><button class="btn btn-ghost btn-sm" data-add-movdoc style="margin-top:6px">+ Добавить документ</button>'}
function docsTab(){return splitWrap((state.viewer&&state.viewerDoc&&state.viewerDoc.scope==='oc')?viewerHTML():null,'<div class="card t-slate"><div class="card-head"><span class="card-idx">03</span><h3>Перечень документов</h3><span class="hint">клик по строке — просмотрщик</span><div class="dd" style="margin-left:auto"><button class="btn btn-primary btn-sm" data-dd-toggle>+ Прикрепить документ</button><div class="dd-menu">'+DOC_TYPES.map(t=>'<button data-attach="'+esc(t)+'">'+esc(t)+'</button>').join('')+'</div></div></div>'+docsTableHTML(true)+'<div class="muted" style="font-size:10.5px;padding:8px 14px 12px">Документы прикрепляются к ОЦ и доступны всем литерам.</div></div>')}
function headOC(){return '<div class="card card-pad t-blue"><div class="head-meta"><span class="pill pill-cat">'+esc(OC.category)+'</span><div class="hm"><label>Тип ОЦ</label><b>'+esc(OC.type)+'</b></div><div class="hm"><label>Назначение по ТП</label><b>'+esc(OC.purposeTP)+'</b></div><div class="hm"><label>Код ЕНИ</label><b>'+esc(OC.eni)+'</b></div><div class="hm"><label>Адрес</label><b>'+esc(OC.address)+'</b></div><span class="pill pill-status" style="margin-left:auto"><span class="dot"></span>'+esc(OC.status)+'</span><div class="dd" id="ddAddOi"><button class="btn btn-primary" data-dd-toggle>+ Добавить ОИ</button><div class="dd-menu"><div class="dd-group">Недвижимость</div>'+REALTY_TYPES.map(t=>'<button data-add-oi="'+esc(t)+'">'+esc(t)+'</button>').join('')+(OC.complex?'<div class="dd-group">Движимое имущество</div><button data-add-oi="МЕХ">Механизмы и производственное оборудование</button><button data-add-oi="ОФИС">Офисная техника и мебель</button>':'')+'</div></div><button class="btn btn-ghost" id="btnEditOc">Редактировать</button><button class="btn btn-danger" id="btnDelOc">Удалить</button></div></div>'}
function viewOC(){return headOC()+'<div class="tabs"><button class="tab '+(state.tab==='general'?'active':'')+'" data-tab="general">Общие данные</button><button class="tab '+(state.tab==='docs'?'active':'')+'" data-tab="docs">Документы '+DOCS.length+'</button><button class="tab '+(state.tab==='photo'?'active':'')+'" data-tab="photo">Фото</button></div>'+(state.tab==='general'?partiesOC()+tableOI():state.tab==='docs'?docsTab():photosTab())}
function structField(key,label,opts,val,req){const isOther=String(val).includes('Прочее');return '<div class="field"><label>'+label+(req?'<span class="req">*</span>':'')+'</label><select class="select" data-struct="'+key+'">'+opts.map(o=>'<option '+(o===val?'selected':'')+'>'+o+'</option>').join('')+'</select>'+(isOther?'<input class="input" placeholder="Укажите вручную" value="">':'')+'</div>'}
function heatingMS(oi){return '<div class="field"><label>Отопление (мультивыбор)</label><div class="ms"><div class="ms-control" data-ms-control data-ms-toggle>'+(oi.heating.length?oi.heating.map(h=>'<span class="ms-tag">'+esc(h)+'&nbsp;<span data-heat-rm="'+esc(h)+'">×</span></span>').join('')+'<span class="ms-add">+ выбрать</span>':'<span class="muted">не выбрано</span><span class="ms-add">+ выбрать</span>')+'</div><div class="ms-drop" '+(state.heatOpen?'':'hidden')+'>'+HEATING.map(h=>'<label class="ms-opt"><input type="checkbox" data-heat-opt="'+esc(h)+'" '+(oi.heating.includes(h)?'checked':'')+'>'+esc(h)+'</label>').join('')+'</div></div>'+(oi.heating.includes('Прочее (ручной ввод)')?'<input class="input" data-heat-other placeholder="Укажите отопление вручную" value="'+esc(oi.heatingOther)+'" style="margin-top:5px">':'')+'</div>'}
function floorsBlock(oi){const s=floorsSum(oi),t=num(oi.areas.tp);const ok=Math.abs(s-t)<0.01;const fkey='fl|'+oi.id;const anyAuto=(oi.floorList||[]).some(f=>f.on);const open=state.accOpen[fkey]===true||(state.accOpen[fkey]===undefined&&(oi.floors>1||anyAuto));
 return '<div class="field" style="max-width:220px"><label>Количество этажей</label><input class="input" data-floors-n value="'+oi.floors+'" inputmode="numeric"></div><div class="acc '+(open?'open':'')+'" style="margin-top:6px"><div class="acc-head" data-acc-toggle="'+fkey+'"><span class="chev">▾</span>Поэтажная развёртка (включая подвал, мансарду, цоколь)<span style="margin-left:auto" data-floor-sum class="'+(ok?'sum-ok':'sum-warn')+'">Σ этажей: '+fmt(s)+' / '+fmt(t)+' м²</span><button class="btn btn-ghost btn-sm" data-redistribute style="margin-left:8px">Выровнять отмеченные</button></div><div class="acc-body" style="padding:8px"><table class="tbl"><thead><tr><th style="width:30px"></th><th>Этаж</th><th style="width:120px">Площадь, м²</th><th style="width:120px">Высота внешн, м</th><th style="width:120px">Высота внутр, м</th></tr></thead><tbody>'+(oi.floorList||[]).map((f,i)=>'<tr><td><input type="checkbox" data-floor-on="'+i+'" '+(f.on?'checked':'')+'></td><td>'+esc(f.name)+(f.special?' <span class="tag-mini">вручную</span>':'')+'</td><td><input class="input" data-floor-area="'+i+'" value="'+esc(f.area)+'" '+(f.special||f.on?'':'disabled')+'></td><td><input class="input" data-floor-hext="'+i+'" value="'+esc(f.hExt)+'"></td><td><input class="input" data-floor-hint="'+i+'" value="'+esc(f.hInt)+'"></td></tr>').join('')+'</tbody></table><div class="muted" style="font-size:10.5px;margin-top:5px">Отмеченные получают остаток поровну; снятый чекбокс = площадь вручную.</div></div></div>'}
function realtyCards(oi){const rq=requiredFlags(oi);const f=oi.flags||{};
 return '<div class="oi-stack"><div class="card t-blue" id="q-gen"><div class="card-head" data-card-toggle><span class="card-idx">01</span><h3>Общие параметры</h3><span class="letter-badge">'+esc(oi.letter)+'</span><span class="hint">'+esc(oi.name)+'</span><span class="chev">▾</span></div><div class="card-body-wrap"><div class="card-pad"><div class="inline-row" style="margin-bottom:10px">'+(state.letterEdit?'<input class="input" style="width:80px;text-align:center;font-weight:700" data-letter-input value="'+esc(oi.letter)+'"><button class="btn btn-primary btn-sm" data-letter-save>Сохранить</button><button class="btn btn-ghost btn-sm" data-letter-cancel>Отмена</button>':'<button class="btn btn-ghost btn-sm" data-edit-letter>✎ Переименовать</button>')+'<input class="input" style="max-width:240px" data-oi-name value="'+esc(oi.name)+'"><select class="select" style="max-width:150px" data-status>'+DICT.statusBuild.map(o=>'<option '+(o===oi.status?'selected':'')+'>'+o+'</option>').join('')+'</select><input class="eni-corner" data-oi-eni value="'+esc(oi.eni)+'"></div><div class="inline-row" style="margin-bottom:10px"><label class="flag-lbl"><input type="checkbox" data-flag="entered" '+(f.entered?'checked':'')+'> Введено</label><label class="flag-lbl"><input type="checkbox" data-flag="matched" '+(f.matched?'checked':'')+'> Сопоставлено с фото</label></div><div class="grid g-3"><div class="field"><label>Год постройки</label><input class="input" data-year value="'+esc(oi.year||'')+'" inputmode="numeric"></div><div class="field"><label>Тип строения'+(rq.buildType?'<span class="req">*</span>':'')+'</label><select class="select" data-buildtype>'+DICT.buildType.map(o=>'<option '+(o===oi.buildType?'selected':'')+'>'+o+'</option>').join('')+'</select></div><div class="field"><label>Категория ОИ</label><select class="select" data-catclass '+(oi.dis?'':'disabled')+'>'+CATCLASS.map(o=>'<option '+(o===(oi.catClass||'Гражданское')?'selected':'')+'>'+o+'</option>').join('')+'</select><label class="inline-row" style="font-size:10.5px;font-weight:400"><input type="checkbox" data-dis '+(oi.dis?'checked':'')+'> расхождение ТП и фото</label></div></div></div></div></div>'+
 '<div class="card t-blue" id="q-areas"><div class="card-head" data-card-toggle><span class="card-idx">02</span><h3>Площади и этажность</h3><span class="chev">▾</span></div><div class="card-body-wrap"><div class="card-pad"><div class="grid g-4"><div class="field"><label>Общая по техпаспорту, м²</label><input class="input" data-area="tp" value="'+esc(oi.areas.tp)+'"></div><div class="field"><label>Общая по ПУД, м²</label><input class="input" data-area="pud" value="'+esc(oi.areas.pud)+'"></div><div class="field"><label>Общая по факту, м²</label><input class="input" data-area="fact" value="'+esc(oi.areas.fact)+'"></div><div class="field"><label>Площадь застройки, м²</label><input class="input" data-area="build" value="'+esc(oi.areas.build)+'"></div></div><div style="margin-top:10px">'+floorsBlock(oi)+'</div><div class="grid g-2" style="margin-top:10px"><div class="field"><label>Высота по внешним замерам, м'+(rq.height?'<span class="req">*</span>':'')+'</label><input class="input" data-height="ext" value="'+esc(oi.heights.ext)+'"></div><div class="field"><label>Высота по внутренним замерам, м</label><input class="input" data-height="int" value="'+esc(oi.heights.int)+'"></div></div></div></div></div>'+
 '<div class="card t-teal" id="q-struct"><div class="card-head" data-card-toggle><span class="card-idx">03</span><h3>Конструктивный состав</h3><span class="chev">▾</span></div><div class="card-body-wrap"><div class="card-pad"><div class="grid g-4">'+structField('foundation','Фундамент',DICT.foundation,oi.struct.foundation)+structField('wallsExt','Наружные стены',DICT.wallsExt,oi.struct.wallsExt,rq.walls)+structField('ceilings','Перекрытия',DICT.ceilings,oi.struct.ceilings)+structField('roof','Кровля',DICT.roof,oi.struct.roof)+'</div><div class="grid g-4" style="margin-top:8px">'+structField('floors','Полы',DICT.floors,oi.struct.floors)+structField('windows','Окна',DICT.windows,oi.struct.windows)+structField('doors','Двери',DICT.doors,oi.struct.doors)+heatingMS(oi)+'</div><div class="field" style="margin-top:8px"><label>Комментарий</label><textarea class="textarea" data-comment>'+esc(oi.comment||'')+'</textarea></div></div></div></div>'+
 '<div class="card t-slate" id="q-prem"><div class="card-head" data-card-toggle><span class="card-idx">04</span><h3>Помещения</h3><span class="chev">▾</span></div><div class="card-body-wrap"><div class="card-pad"><table class="tbl"><thead><tr><th style="width:190px">Категория</th><th>Наименование</th><th style="width:120px">Площадь, м²</th><th style="width:36px"></th></tr></thead><tbody>'+oi.premises.map((p,i)=>'<tr><td><select class="select" data-prem-cat="'+i+'">'+PREM_CAT.map(c=>'<option '+(c===p.cat?'selected':'')+'>'+c+'</option>').join('')+'</select></td><td><input class="input" data-prem-name="'+i+'" value="'+esc(p.name)+'"></td><td><input class="input" data-prem-area="'+i+'" value="'+esc(p.area)+'"></td><td><button class="btn btn-ghost btn-sm" data-prem-del="'+i+'">×</button></td></tr>').join('')+'</tbody></table><button class="btn btn-ghost btn-sm" data-prem-add style="margin-top:6px">+ Добавить помещение</button></div></div></div>'+
 '<div class="card t-slate" id="q-docs"><div class="card-head" data-card-toggle><span class="card-idx">05</span><h3>Документы ОЦ</h3><span class="hint">документы общие для всех литер</span><span class="chev">▾</span></div><div class="card-body-wrap"><div class="card-pad">'+docsBlockInner(oi,'oc')+'</div></div></div>'+
 '<div class="card t-blue" id="q-photo"><div class="card-head" data-card-toggle><span class="card-idx">06</span><h3>Фото по категориям</h3><button class="btn btn-ghost btn-sm" data-open-pviewer style="margin-left:auto">Открыть просмотрщик</button><span class="chev">▾</span></div><div class="card-body-wrap"><div class="card-pad">'+photoAccordions(oi,true)+'</div></div></div></div>'}
function movableCards(oi){const f=oi.flags||{};return '<div class="oi-stack"><div class="card t-blue"><div class="card-head"><span class="card-idx">01</span><h3>Данные</h3></div><div class="card-pad"><div class="inline-row" style="margin-bottom:10px"><label class="flag-lbl"><input type="checkbox" data-flag="entered" '+(f.entered?'checked':'')+'> Введено</label><label class="flag-lbl"><input type="checkbox" data-flag="matched" '+(f.matched?'checked':'')+'> Сопоставлено с фото</label></div><div class="grid g-3"><div class="field"><label>Наименование</label><input class="input" data-mv-name value="'+esc(oi.name)+'"></div><div class="field"><label>Год выпуска</label><input class="input" data-mv-year value="'+esc(oi.year||'')+'"></div><div class="field"><label>Заводской / инв. номер</label><input class="input" data-mv-serial value="'+esc(oi.serial||'')+'"></div></div></div></div><div class="card t-slate"><div class="card-head"><span class="card-idx">02</span><h3>Документы</h3></div><div class="card-pad">'+docsBlockInner(oi,oi.id)+'</div></div></div>'}
function landCards(oi){return '<div class="oi-stack"><div class="card t-teal"><div class="card-head"><span class="card-idx">01</span><h3>Земельный участок (один ЕНИ)</h3></div><div class="card-pad"><div class="grid g-3"><div class="field"><label>Назначение</label><input class="input" data-land-purpose value="'+esc(oi.purpose)+'"></div><div class="field"><label>Общая площадь, м²</label><input class="input" data-land-area value="'+esc(oi.area)+'"></div><div class="field"><label>ЕНИ</label><input class="input" readonly value="'+esc(oi.eni)+'"></div></div></div></div><div class="card t-slate"><div class="card-head"><span class="card-idx">02</span><h3>Документы</h3></div><div class="card-pad">'+docsBlockInner(oi,oi.id)+'</div></div></div>'}
function viewOI(){const oi=currentOI();if(!oi)return viewOC();const isR=oi.kind==='realty';const f=oi.flags||{};
 return '<div class="view-head"><button class="back-btn" data-back>← К объекту оценки</button><span class="pill pill-gray">'+(isR?'Карточка ОИ (литера)':oi.kind==='land'?'Земельный участок':'Механизм')+'</span>'+(isR?'<label class="flag-lbl"><input type="checkbox" data-flag="entered" '+(f.entered?'checked':'')+'> Введено</label><label class="flag-lbl"><input type="checkbox" data-flag="matched" '+(f.matched?'checked':'')+'> Сопоставлено с фото</label>':'')+(isR?'<button class="btn btn-danger" data-del-oi="'+oi.id+'">Удалить литеру</button>':'')+'<button class="btn btn-ghost" data-open-ocdocs>Документы ОЦ</button><button class="btn btn-primary" data-save-oi>Сохранить</button><button class="btn btn-ghost" data-back>Отмена</button></div>'+splitWrap(state.viewer?(state.moveWizard?moveWizardHTML():viewerHTML()):null,(isR?realtyCards(oi):oi.kind==='land'?landCards(oi):movableCards(oi)))}
function viewOCForm(){const mov=OC.category==='Движимое';
 return '<div class="view-head"><button class="back-btn" data-back>← К карточке объекта</button><span class="pill pill-gray">Редактирование ОЦ · '+esc(OC.eni)+'</span><button class="btn btn-primary" id="btnSaveOc">Сохранить и вернуться</button><button class="btn btn-ghost" data-back>Отмена</button></div>'+splitWrap((state.viewer&&state.viewerDoc&&state.viewerDoc.scope==='oc')?viewerHTML():null,'<div class="oi-stack"><div class="card t-blue"><div class="card-head"><span class="card-idx">01</span><h3>Основные параметры</h3></div><div class="card-pad"><div class="grid g-3"><div class="field"><label>Тип ОЦ</label><select class="select" id="fType">'+['Жилое здание (дом)','Гражданское здание','Производственное строение','Прочее строение'].map(t=>'<option '+(t===OC.type?'selected':'')+'>'+t+'</option>').join('')+'</select></div><div class="field"><label>Назначение по ТП</label><input class="input" id="fPurpose" value="'+esc(OC.purposeTP)+'"></div><div class="field"><label>Статус ОЦ</label><select class="select" id="fStatus">'+DICT.statusOC.map(s=>'<option '+(s===OC.status?'selected':'')+'>'+s+'</option>').join('')+'</select></div></div><div class="grid g-4" style="margin-top:10px"><div class="field"><label>Категория ОЦ</label><select class="select" id="fCat">'+['Недвижимое','Движимое','Имущественный комплекс'].map(c=>'<option '+(c===OC.category?'selected':'')+'>'+c+'</option>').join('')+'</select></div><div class="field"><label>Код ЕНИ</label><input class="input" id="fEni" value="'+esc(OC.eni)+'"></div><div class="field"><label>Учреждение</label><input class="input" id="fInst" value="'+esc(OC.institution)+'"></div><div class="field"><label>Подвед</label><input class="input" id="fPodved" value="'+esc(OC.podved)+'"></div></div><div class="grid g-2" style="margin-top:10px"><div class="field"><label>Адрес</label><input class="input" id="fAddr" value="'+esc(OC.address)+'"></div><div class="field"><label>GPS</label><input class="input" id="fGps" value="'+esc(OC.gps)+'"></div></div></div></div><div class="card t-slate"><div class="card-head"><span class="card-idx">02</span><h3>Собственники и ответственные</h3></div><div class="card-pad">'+ownersUsersHTML()+'<div class="sec-h">Ответственные</div>'+responsiblesHTML()+'</div></div><div class="card t-slate"><div class="card-head"><span class="card-idx">03</span><h3>Документы ОЦ</h3></div>'+docsTableHTML(true)+'</div></div>')}
function viewMech(){const isMech=state.mechKind==='МЕХ';
 return '<div class="view-head"><button class="back-btn" data-back>← Отмена</button><span class="pill pill-gray">'+(isMech?'Механизмы':'Офисная техника')+'</span></div>'+splitWrap((state.viewer&&state.viewerDoc&&state.viewerDoc.scope==='mech-new')?viewerHTML():null,'<div class="card"><div class="card-head"><h3>Создание объекта</h3><div class="inline-row" style="margin-left:auto"><span class="qn" data-mech-mode="mono">Монолит</span><span class="qn" data-mech-mode="complex">Комплекс</span></div></div><div class="card-pad">'+(state.mechMode==='mono'?'<div class="grid g-3"><div class="field"><label>Наименование</label><input class="input" id="mName"></div><div class="field"><label>Год</label><input class="input" id="mYear"></div><div class="field"><label>Заводской номер</label><input class="input" id="mSerial"></div></div>'+docsBlockInner({docs:state.mechDocs||[]},'mech-new'):'<table class="tbl"><thead><tr><th>Наименование ОИ</th><th>Тип</th><th>Код ЕНИ</th><th></th></tr></thead><tbody id="mechRows"></tbody></table><button class="btn btn-ghost btn-sm" data-mech-add style="margin-top:6px">+ Добавить ОИ</button>')+'<div class="inline-row" style="margin-top:14px"><button class="btn btn-primary" data-mech-save>Создать</button><button class="btn btn-ghost" data-back>Отмена</button></div></div></div>')}
function render(){const c=$('#content');let body=''; if(state.view==='oc')body=viewOC(); else if(state.view==='oi')body=viewOI(); else if(state.view==='ocform')body=viewOCForm(); else body=viewMech(); $('#crumbs').innerHTML=crumbsHTML(); const plate=ctxPlate(); c.innerHTML='<div id="ctxPlateWrap" style="'+(plate?'':'display:none')+'">'+(plate||'')+'</div>'+body; syncDrawer(); bind();}
function syncDrawer(){const dr=$('#notesDrawer');const show=(state.view==='oc'&&state.tab==='general')||state.view==='oi'; if(show){dr.classList.remove('hidden');dr.classList.toggle('open',state.notesOpen);$('#drawerNotes').innerHTML=drawerNotesHTML();const c=$('#drawerCount');if(c){const tp=totalPendingNotes();c.textContent=tp;c.className='pill-mini '+(tp?'pill-pend':'pill-done');}} else dr.classList.add('hidden');}